export const ADD_COMMENT = 'ADD_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const DISHES_LOADING = 'DISHES_LOADING';
export const DISHES_FAILDED = 'DISHES_FAILED';
export const ADD_DISHES = 'ADD_DISHES';
